AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - bin/**/*
    - spec/dummy/**/*
    - example/**/*

Lint/SpaceBeforeFirstArg:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
