language: ruby
rvm:
  - 2.2.4
  - 2.3.0
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
before_script:
  - ./bootstrap
cache: bundler
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.0.beta2.gemfile
