language: ruby
sudo: false
bundler_args: "--binstubs --without documentation --retry=3"
before_script:
   - bundle install
gemfile:
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
